name: RPI5-ALL

on:
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      TEST:
        description: 'Only output config file, do not compile firmware.'
        default: 'false'
        required: false
        type: boolean

permissions: write-all

jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      # max-parallel: 3
      matrix:
        CONFIG: [RPI5M, RPI5]
        SOURCE: [AW1Kdev/DOTYPI5]
        BRANCH: [main]

    uses: ./.github/workflows/RPI5-CORE.yml
    with:
      WRT_CONFIG: ${{matrix.CONFIG}}
      WRT_IP: 192.168.10.1
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      WRT_BRANCH: ${{matrix.BRANCH}}
      WRT_SOURCE: ${{matrix.SOURCE}}
      WRT_TEST: ${{inputs.TEST}}
